import { CostCategory, ISkillProps } from './SkillDefinitions';

const skillData: ISkillProps[] = [
  {
    name: "Sword Mastery",
    category: "Combat",
    level: 5,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 50,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Alchemy",
    category: "Crafting",
    level: 3,
    is_active: false,
    cost_category: CostCategory.EXPENSIVE,
    cost: 120,
    is_edited: true,
    edited_level: 4,
  },
  {
    name: "Stealth",
    category: "Subterfuge",
    level: 7,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 20,
    is_edited: false,
    edited_level: 7,
  },
  {
    name: "Herbalism",
    category: "Nature",
    level: 2,
    is_active: true,
    cost_category: CostCategory.FREE,
    cost: 0,
    is_edited: false,
    edited_level: 2,
  },
  {
    name: "Magic Casting",
    category: "Magic",
    level: 8,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 200,
    is_edited: true,
    edited_level: 9,
  },
  {
    name: "Archery",
    category: "Combat",
    level: 4,
    is_active: false,
    cost_category: CostCategory.NORMAL,
    cost: 60,
    is_edited: false,
    edited_level: 4,
  },
  {
    name: "Blacksmithing",
    category: "Crafting",
    level: 6,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 150,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Lockpicking",
    category: "Subterfuge",
    level: 5,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: true,
    edited_level: 6,
  },
  {
    name: "Healing",
    category: "Magic",
    level: 6,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 70,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Fishing",
    category: "Nature",
    level: 1,
    is_active: true,
    cost_category: CostCategory.FREE,
    cost: 0,
    is_edited: true,
    edited_level: 2,
  },
];

export default skillData;
