import { CostCategory, ISkillProps } from './SkillDefinitions';

const skillData: ISkillProps[] = [
  {
    name: "Athletik",
    category: "Athletik",
    level: 3,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: false,
    edited_level: 3,
  },
  {
    name: "Akrobatik",
    category: "Athletik",
    level: 7,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 40,
    is_edited: true,
    edited_level: 8,
  },
  {
    name: "Gaukeleien",
    category: "Gesellschaft",
    level: 4,
    is_active: false,
    cost_category: CostCategory.LOW_PRICED,
    cost: 20,
    is_edited: false,
    edited_level: 4,
  },
  {
    name: "Klettern",
    category: "Natur",
    level: 6,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 50,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Körperbeherrschung",
    category: "Athletik",
    level: 8,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 100,
    is_edited: true,
    edited_level: 9,
  },
  {
    name: "Reiten",
    category: "Natur",
    level: 5,
    is_active: false,
    cost_category: CostCategory.NORMAL,
    cost: 60,
    is_edited: false,
    edited_level: 5,
  },
  {
    name: "Schleichen",
    category: "Subterfuge",
    level: 7,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: true,
    edited_level: 8,
  },
  {
    name: "Schwimmen",
    category: "Athletik",
    level: 6,
    is_active: true,
    cost_category: CostCategory.FREE,
    cost: 0,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Selbstbeherrschung",
    category: "Gesellschaft",
    level: 4,
    is_active: false,
    cost_category: CostCategory.NORMAL,
    cost: 50,
    is_edited: true,
    edited_level: 5,
  },
  {
    name: "Sich verstecken",
    category: "Subterfuge",
    level: 8,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 100,
    is_edited: false,
    edited_level: 8,
  },
  {
    name: "Singen",
    category: "Gesellschaft",
    level: 2,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 20,
    is_edited: true,
    edited_level: 3,
  },
  {
    name: "Sinnenschärfe",
    category: "Natur",
    level: 5,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 60,
    is_edited: false,
    edited_level: 5,
  },
  {
    name: "Stimmen Imitieren",
    category: "Gesellschaft",
    level: 3,
    is_active: false,
    cost_category: CostCategory.NORMAL,
    cost: 40,
    is_edited: false,
    edited_level: 3,
  },
  {
    name: "Tanzen",
    category: "Gesellschaft",
    level: 6,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: true,
    edited_level: 7,
  },
  {
    name: "Zechen",
    category: "Gesellschaft",
    level: 4,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 120,
    is_edited: false,
    edited_level: 4,
  },
  {
    name: "Taschendiebstahl",
    category: "Subterfuge",
    level: 5,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 20,
    is_edited: false,
    edited_level: 5,
  },
  {
    name: "Betören",
    category: "Gesellschaft",
    level: 7,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 100,
    is_edited: true,
    edited_level: 8,
  },
  {
    name: "Etikette",
    category: "Gesellschaft",
    level: 6,
    is_active: false,
    cost_category: CostCategory.NORMAL,
    cost: 50,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Lehren",
    category: "Gesellschaft",
    level: 8,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 70,
    is_edited: true,
    edited_level: 9,
  },
  {
    name: "Schauspielerei",
    category: "Gesellschaft",
    level: 5,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 120,
    is_edited: false,
    edited_level: 5,
  },
  {
    name: "Schriftlicher Ausdruck",
    category: "Gesellschaft",
    level: 6,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: true,
    edited_level: 7,
  },
  {
    name: "Sich verkleiden",
    category: "Subterfuge",
    level: 4,
    is_active: false,
    cost_category: CostCategory.NORMAL,
    cost: 40,
    is_edited: false,
    edited_level: 4,
  },
  {
    name: "Gassenwissen",
    category: "Natur",
    level: 3,
    is_active: true,
    cost_category: CostCategory.FREE,
    cost: 0,
    is_edited: false,
    edited_level: 3,
  },
  {
    name: "Menschenkenntnis",
    category: "Gesellschaft",
    level: 8,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 150,
    is_edited: true,
    edited_level: 9,
  },
  {
    name: "Überreden",
    category: "Gesellschaft",
    level: 5,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 60,
    is_edited: false,
    edited_level: 5,
  },
  {
    name: "Überzeugen",
    category: "Gesellschaft",
    level: 4,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: true,
    edited_level: 5,
  },
  {
    name: "Fährtensuchen",
    category: "Natur",
    level: 7,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 100,
    is_edited: false,
    edited_level: 7,
  },
  {
    name: "Fesseln / Entfesseln",
    category: "Natur",
    level: 6,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 50,
    is_edited: true,
    edited_level: 7,
  },
  {
    name: "Fallen stellen",
    category: "Natur",
    level: 3,
    is_active: false,
    cost_category: CostCategory.LOW_PRICED,
    cost: 20,
    is_edited: false,
    edited_level: 3,
  },
  {
    name: "Fischen / Angeln",
    category: "Natur",
    level: 8,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 60,
    is_edited: false,
    edited_level: 8,
  },
  {
    name: "Orientierung",
    category: "Natur",
    level: 4,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: false,
    edited_level: 4,
  },
  {
    name: "Wildnisleben",
    category: "Natur",
    level: 6,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 120,
    is_edited: true,
    edited_level: 7,
  },
  {
    name: "Anatomie",
    category: "Wissen",
    level: 5,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 50,
    is_edited: false,
    edited_level: 5,
  },
  {
    name: "Baukunst",
    category: "Wissen",
    level: 3,
    is_active: false,
    cost_category: CostCategory.LOW_PRICED,
    cost: 40,
    is_edited: false,
    edited_level: 3,
  },
  {
    name: "Geographie",
    category: "Wissen",
    level: 4,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 50,
    is_edited: true,
    edited_level: 5,
  },
  {
    name: "Geschichtswissen",
    category: "Wissen",
    level: 7,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 100,
    is_edited: true,
    edited_level: 8,
  },
  {
    name: "Gesteinskunde",
    category: "Wissen",
    level: 6,
    is_active: false,
    cost_category: CostCategory.NORMAL,
    cost: 60,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Pflanzenkunde",
    category: "Wissen",
    level: 3,
    is_active: true,
    cost_category: CostCategory.FREE,
    cost: 0,
    is_edited: false,
    edited_level: 3,
  },
  {
    name: "Philosophie",
    category: "Wissen",
    level: 8,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 70,
    is_edited: false,
    edited_level: 8,
  },
  {
    name: "Sternkunde",
    category: "Wissen",
    level: 5,
    is_active: true,
    cost_category: CostCategory.LOW_PRICED,
    cost: 40,
    is_edited: true,
    edited_level: 6,
  },
  {
    name: "Rechnen",
    category: "Wissen",
    level: 4,
    is_active: false,
    cost_category: CostCategory.EXPENSIVE,
    cost: 100,
    is_edited: false,
    edited_level: 4,
  },
  {
    name: "Rechtskunde",
    category: "Wissen",
    level: 6,
    is_active: true,
    cost_category: CostCategory.NORMAL,
    cost: 70,
    is_edited: false,
    edited_level: 6,
  },
  {
    name: "Schätzen",
    category: "Wissen",
    level: 5,
    is_active: false,
    cost_category: CostCategory.LOW_PRICED,
    cost: 30,
    is_edited: false,
    edited_level: 5,
  },
  {
    name: "Tierkunde",
    category: "Wissen",
    level: 7,
    is_active: true,
    cost_category: CostCategory.EXPENSIVE,
    cost: 120,
    is_edited: true,
    edited_level: 8,
  },
];

export default skillData;
