import { Attribute, BaseValue, CharacterSheet, CombatValues, Skill } from "shared";
import {
  ATTRIBUTE_POINTS_FOR_CREATION,
  COST_CATEGORY_COMBAT_SKILLS,
  COST_CATEGORY_DEFAULT,
  combatSkills,
  startSkills,
} from "./rules.js";

export function createEmptyCharacterSheet(): CharacterSheet {
  const zeroAttribute = (): Attribute => ({ start: 0, current: 0, mod: 0, totalCost: 0 });
  const zeroBaseValue = (): BaseValue => ({ start: 0, current: 0, mod: 0 }); // TODO by formula and byLvlUp. See baseValueFormulas and baseValuesNotUpdatableByLvlUp

  const zeroSkill = (skillName: string): Skill => {
    return {
      activated: startSkills.includes(skillName) ? true : false,
      start: 0,
      current: 0,
      mod: 0,
      totalCost: 0,
      defaultCostCategory: (combatSkills as string[]).includes(skillName)
        ? COST_CATEGORY_COMBAT_SKILLS
        : COST_CATEGORY_DEFAULT,
    } as Skill;
  };

  const zeroCombatValues = (): CombatValues => ({
    availablePoints: 0,
    attackValue: 0,
    paradeValue: 0,
  });

  return {
    generalInformation: {
      name: "",
      level: 0,
      sex: "",
      profession: { name: "", skill: "" },
      hobby: { name: "", skill: "" },
      birthday: "",
      birthplace: "",
      size: "",
      weight: "",
      hairColor: "",
      eyeColor: "",
      residence: "",
      appearance: "",
      specialCharacteristics: "",
    },
    calculationPoints: {
      adventurePoints: { start: ATTRIBUTE_POINTS_FOR_CREATION, available: 0, total: ATTRIBUTE_POINTS_FOR_CREATION },
      attributePoints: { start: 0, available: 0, total: 0 },
    },
    advantages: [],
    disadvantages: [],
    specialAbilities: new Set<string>(),
    baseValues: {
      healthPoints: zeroBaseValue(),
      mentalHealth: zeroBaseValue(),
      armorLevel: zeroBaseValue(),
      naturalArmor: zeroBaseValue(),
      initiativeBaseValue: zeroBaseValue(),
      attackBaseValue: zeroBaseValue(),
      paradeBaseValue: zeroBaseValue(),
      rangedAttackBaseValue: zeroBaseValue(),
      luckPoints: zeroBaseValue(),
      bonusActionsPerCombatRound: zeroBaseValue(),
      legendaryActions: zeroBaseValue(),
    },
    attributes: {
      courage: zeroAttribute(),
      intelligence: zeroAttribute(),
      concentration: zeroAttribute(),
      charisma: zeroAttribute(),
      mentalResilience: zeroAttribute(),
      dexterity: zeroAttribute(),
      endurance: zeroAttribute(),
      strength: zeroAttribute(),
    },
    skills: {
      combat: {
        martialArts: zeroSkill("martialArts"),
        barehanded: zeroSkill("barehanded"),
        chainWeapons: zeroSkill("chainWeapons"),
        daggers: zeroSkill("daggers"),
        slashingWeaponsSharp1h: zeroSkill("slashingWeaponsSharp1h"),
        slashingWeaponsBlunt1h: zeroSkill("slashingWeaponsBlunt1h"),
        thrustingWeapons1h: zeroSkill("thrustingWeapons1h"),
        slashingWeaponsSharp2h: zeroSkill("slashingWeaponsSharp2h"),
        slashingWeaponsBlunt2h: zeroSkill("slashingWeaponsBlunt2h"),
        thrustingWeapons2h: zeroSkill("thrustingWeapons2h"),
        missile: zeroSkill("missile"),
        firearmSimple: zeroSkill("firearmSimple"),
        firearmMedium: zeroSkill("firearmMedium"),
        firearmComplex: zeroSkill("firearmComplex"),
        heavyWeapons: zeroSkill("heavyWeapons"),
      },
      body: {
        athletics: zeroSkill("athletics"),
        juggleries: zeroSkill("juggleries"),
        climbing: zeroSkill("climbing"),
        bodyControl: zeroSkill("bodyControl"),
        riding: zeroSkill("riding"),
        sneaking: zeroSkill("sneaking"),
        swimming: zeroSkill("swimming"),
        selfControl: zeroSkill("selfControl"),
        hiding: zeroSkill("hiding"),
        singing: zeroSkill("singing"),
        sharpnessOfSenses: zeroSkill("sharpnessOfSenses"),
        dancing: zeroSkill("dancing"),
        quaffing: zeroSkill("quaffing"),
        pickpocketing: zeroSkill("pickpocketing"),
      },
      social: {
        seduction: zeroSkill("seduction"),
        etiquette: zeroSkill("etiquette"),
        teaching: zeroSkill("teaching"),
        acting: zeroSkill("acting"),
        writtenExpression: zeroSkill("writtenExpression"),
        streetKnowledge: zeroSkill("streetKnowledge"),
        knowledgeOfHumanNature: zeroSkill("knowledgeOfHumanNature"),
        persuading: zeroSkill("persuading"),
        convincing: zeroSkill("convincing"),
      },
      nature: {
        tracking: zeroSkill("tracking"),
        knottingSkills: zeroSkill("knottingSkills"),
        trapping: zeroSkill("trapping"),
        fishing: zeroSkill("fishing"),
        orientation: zeroSkill("orientation"),
        wildernessLife: zeroSkill("wildernessLife"),
      },
      knowledge: {
        anatomy: zeroSkill("anatomy"),
        architecture: zeroSkill("architecture"),
        geography: zeroSkill("geography"),
        history: zeroSkill("history"),
        petrology: zeroSkill("petrology"),
        botany: zeroSkill("botany"),
        philosophy: zeroSkill("philosophy"),
        astronomy: zeroSkill("astronomy"),
        mathematics: zeroSkill("mathematics"),
        knowledgeOfTheLaw: zeroSkill("knowledgeOfTheLaw"),
        estimating: zeroSkill("estimating"),
        zoology: zeroSkill("zoology"),
        technology: zeroSkill("technology"),
        chemistry: zeroSkill("chemistry"),
        warfare: zeroSkill("warfare"),
        itSkills: zeroSkill("itSkills"),
        mechanics: zeroSkill("mechanics"),
      },
      handcraft: {
        training: zeroSkill("training"),
        woodwork: zeroSkill("woodwork"),
        foodProcessing: zeroSkill("foodProcessing"),
        leatherProcessing: zeroSkill("leatherProcessing"),
        metalwork: zeroSkill("metalwork"),
        stonework: zeroSkill("stonework"),
        fabricProcessing: zeroSkill("fabricProcessing"),
        alcoholProduction: zeroSkill("alcoholProduction"),
        steeringVehicles: zeroSkill("steeringVehicles"),
        fineMechanics: zeroSkill("fineMechanics"),
        cheating: zeroSkill("cheating"),
        bargaining: zeroSkill("bargaining"),
        firstAid: zeroSkill("firstAid"),
        calmingSbDown: zeroSkill("calmingSbDown"),
        drawingAndPainting: zeroSkill("drawingAndPainting"),
        makingMusic: zeroSkill("makingMusic"),
        lockpicking: zeroSkill("lockpicking"),
      },
    },
    combatValues: {
      melee: {
        martialArts: zeroCombatValues(),
        barehanded: zeroCombatValues(),
        chainWeapons: zeroCombatValues(),
        daggers: zeroCombatValues(),
        slashingWeaponsSharp1h: zeroCombatValues(),
        slashingWeaponsBlunt1h: zeroCombatValues(),
        thrustingWeapons1h: zeroCombatValues(),
        slashingWeaponsSharp2h: zeroCombatValues(),
        slashingWeaponsBlunt2h: zeroCombatValues(),
        thrustingWeapons2h: zeroCombatValues(),
      },
      ranged: {
        missile: zeroCombatValues(),
        firearmSimple: zeroCombatValues(),
        firearmMedium: zeroCombatValues(),
        firearmComplex: zeroCombatValues(),
        heavyWeapons: zeroCombatValues(),
      },
    },
  };
}
