import type { ReactElement } from "react";
import {
  GiJumpAcross,
  GiDiscobolus,
  GiMountainClimbing,
  GiNunFace,
  GiBodyBalance,
  GiHorseHead,
  GiSwimfins,
  GiHoodedFigure,
  GiHoodedAssassin,
  GiSing,
  GiAwareness,
  GiSpikedHalo,
  GiBeerStein,
  GiHand,
  GiRoundTable,
  GiWrappedHeart,
  GiInspiration,
  GiChemicalDrop,
  GiAxeSword,
  GiBackup,
  GiTalk,
  GiTakeMyMoney,
  GiDeerTrack,
  GiRopeCoil,
  GiMantrap,
  GiFishing,
  GiPathDistance,
  GiCampfire,
  GiAnatomy,
  GiBrickWall,
  GiTreasureMap,
  GiStonePile,
  GiPlantSeed,
  GiHumanPyramid,
  GiInternalOrgan,
  GiFallingStar,
  GiCalculator,
  GiInjustice,
  GiHistogram,
  GiBestialFangs,
  GiTinker,
  GiComputing,
  GiMonkeyWrench,
  Gi3dHammer,
  GiBearHead,
  GiBowString,
  GiBeerHorn,
  GiRaceCar,
  GiCardExchange,
  GiMechanicalArm,
  GiAnimalHide,
  GiCoinflip,
  GiFirstAidKit,
  GiDespair,
  GiWoodAxe,
  GiCookingPot,
  GiSewingString,
  GiPencilBrush,
  GiMusicalScore,
  GiCombinationLock,
  GiBookmark,
  GiTeacher,
  GiCarnivalMask,
  GiPencil,
  GiGooeySword,
  GiGraduateCap,
  GiSwordArray,
  GiChainedArrowHeads,
  GiDaggers,
  GiBroadsword,
  GiPistolGun,
  GiMachineGunMagazine,
  GiLaserGun,
  GiCannonBall,
  GiBowArrow,
} from "react-icons/gi";

const iconSize = 20;

const skillIconMap: Record<string, ReactElement> = {
  // Combat skills
  martialArts: <GiSwordArray size={iconSize} />,
  barehanded: <GiHand size={iconSize} />,
  chainWeapons: <GiChainedArrowHeads size={iconSize} />,
  daggers: <GiDaggers size={iconSize} />,
  slashingWeaponsSharp1h: <GiBroadsword size={iconSize} />,
  slashingWeaponsBlunt1h: <GiBroadsword size={iconSize} />,
  thrustingWeapons1h: <GiAxeSword size={iconSize} />,
  slashingWeaponsSharp2h: <GiBroadsword size={iconSize} />,
  slashingWeaponsBlunt2h: <GiBroadsword size={iconSize} />,
  thrustingWeapons2h: <GiAxeSword size={iconSize} />,
  missile: <GiBowArrow size={iconSize} />,
  firearmSimple: <GiPistolGun size={iconSize} />,
  firearmMedium: <GiMachineGunMagazine size={iconSize} />,
  firearmComplex: <GiLaserGun size={iconSize} />,
  heavyWeapons: <GiCannonBall size={iconSize} />,

  // Body skills
  athletics: <GiDiscobolus size={iconSize} />,
  juggleries: <GiNunFace size={iconSize} />,
  climbing: <GiMountainClimbing size={iconSize} />,
  bodyControl: <GiBodyBalance size={iconSize} />,
  riding: <GiHorseHead size={iconSize} />,
  sneaking: <GiHoodedFigure size={iconSize} />,
  swimming: <GiSwimfins size={iconSize} />,
  selfControl: <GiSpikedHalo size={iconSize} />,
  hiding: <GiHoodedAssassin size={iconSize} />,
  singing: <GiSing size={iconSize} />,
  sharpnessOfSenses: <GiAwareness size={iconSize} />,
  dancing: <GiHumanPyramid size={iconSize} />,
  quaffing: <GiBeerStein size={iconSize} />,
  pickpocketing: <GiJumpAcross size={iconSize} />,

  // Social skills
  seduction: <GiWrappedHeart size={iconSize} />,
  etiquette: <GiGraduateCap size={iconSize} />,
  teaching: <GiTeacher size={iconSize} />,
  acting: <GiCarnivalMask size={iconSize} />,
  writtenExpression: <GiPencil size={iconSize} />,
  streetKnowledge: <GiGooeySword size={iconSize} />,
  knowledgeOfHumanNature: <GiBackup size={iconSize} />,
  persuading: <GiTalk size={iconSize} />,
  convincing: <GiTakeMyMoney size={iconSize} />,
  bargaining: <GiCoinflip size={iconSize} />,

  // Nature skills
  tracking: <GiDeerTrack size={iconSize} />,
  knottingSkills: <GiRopeCoil size={iconSize} />,
  trapping: <GiMantrap size={iconSize} />,
  fishing: <GiFishing size={iconSize} />,
  orientation: <GiPathDistance size={iconSize} />,
  wildernessLife: <GiCampfire size={iconSize} />,

  // Knowledge skills
  anatomy: <GiAnatomy size={iconSize} />,
  architecture: <GiBrickWall size={iconSize} />,
  geography: <GiTreasureMap size={iconSize} />,
  history: <GiInspiration size={iconSize} />,
  petrology: <GiStonePile size={iconSize} />,
  botany: <GiPlantSeed size={iconSize} />,
  philosophy: <GiInternalOrgan size={iconSize} />,
  astronomy: <GiFallingStar size={iconSize} />,
  mathematics: <GiCalculator size={iconSize} />,
  knowledgeOfTheLaw: <GiInjustice size={iconSize} />,
  estimating: <GiHistogram size={iconSize} />,
  zoology: <GiBestialFangs size={iconSize} />,
  technology: <GiTinker size={iconSize} />,
  chemistry: <GiChemicalDrop size={iconSize} />,
  warfare: <GiAxeSword size={iconSize} />,
  itSkills: <GiComputing size={iconSize} />,
  mechanics: <GiMonkeyWrench size={iconSize} />,

  // Handcraft skills
  training: <GiBearHead size={iconSize} />,
  woodwork: <GiWoodAxe size={iconSize} />,
  foodProcessing: <GiCookingPot size={iconSize} />,
  leatherProcessing: <GiAnimalHide size={iconSize} />,
  metalwork: <GiBowString size={iconSize} />,
  stonework: <GiBrickWall size={iconSize} />,
  fabricProcessing: <GiSewingString size={iconSize} />,
  alcoholProduction: <GiBeerHorn size={iconSize} />,
  steeringVehicles: <GiRaceCar size={iconSize} />,
  fineMechanics: <GiMechanicalArm size={iconSize} />,
  cheating: <GiCardExchange size={iconSize} />,
  firstAid: <GiFirstAidKit size={iconSize} />,
  calmingSbDown: <GiDespair size={iconSize} />,
  drawingAndPainting: <GiPencilBrush size={iconSize} />,
  makingMusic: <GiMusicalScore size={iconSize} />,
  lockpicking: <GiCombinationLock size={iconSize} />,
};

export function getSkillIcon(skillName: string): ReactElement {
  return skillIconMap[skillName] ?? <GiRoundTable size={iconSize} />;
}

export const skillCategoryIcons: Record<string, ReactElement> = {
  combat: <GiAxeSword size={iconSize} />,
  body: <GiDiscobolus size={iconSize} />,
  social: <GiTalk size={iconSize} />,
  nature: <GiCampfire size={iconSize} />,
  knowledge: <GiBookmark size={iconSize} />,
  handcraft: <Gi3dHammer size={iconSize} />,
};

export const attributeIcons: Record<string, ReactElement> = {
  courage: <GiSwordArray size={iconSize} />,
  intelligence: <GiInspiration size={iconSize} />,
  concentration: <GiAwareness size={iconSize} />,
  charisma: <GiWrappedHeart size={iconSize} />,
  mentalResilience: <GiSpikedHalo size={iconSize} />,
  dexterity: <GiBodyBalance size={iconSize} />,
  endurance: <GiDiscobolus size={iconSize} />,
  strength: <Gi3dHammer size={iconSize} />,
};
