import {
  GiJumpAcross,
  GiDiscobolus,
  GiMountainClimbing,
  GiNunFace,
  GiBodyBalance,
  GiHorseHead,
  GiSwimfins,
  GiHoodedFigure,
  GiHoodedAssassin,
  GiSing,
  GiScreaming,
  GiAwareness,
  GiSpikedHalo,
  GiBeerStein,
  GiHand,
  GiRoundTable,
  GiWrappedHeart,
  GiInspiration,
  GiChemicalDrop,
  GiAxeSword,
  GiBackup,
  GiTalk,
  GiTakeMyMoney,
  GiDeerTrack,
  GiRopeCoil,
  GiMantrap,
  GiFishing,
  GiPathDistance,
  GiCampfire,
  GiAnatomy,
  GiBrickWall,
  GiTreasureMap,
  GiStonePile,
  GiPlantSeed,
  GiHumanPyramid,
  GiInternalOrgan,
  GiFallingStar,
  GiCalculator,
  GiInjustice,
  GiHistogram,
  GiBestialFangs,
  GiTinker,
  GiComputing,
  GiMonkeyWrench,
  Gi3dHammer,
  GiBearHead,
  GiField,
  GiBowString,
  GiBeerHorn,
  GiRaceCar,
  GiCardExchange,
  GiMechanicalArm,
  GiMeatCleaver,
  GiAnimalHide,
  GiCoinflip,
  GiFirstAidKit,
  GiDespair,
  GiWoodAxe,
  GiCookingPot,
  GiSewingString,
  GiPencilBrush,
  GiMusicalScore,
  GiCombinationLock,
  GiBookmark,
  GiTeacher,
  GiCarnivalMask,
  GiPencil,
  GiDominoMask,
  GiGooeySword,
  GiGraduateCap,
} from "react-icons/gi";

/**
 * Returns the appropriate icon for a skill based on its name
 * Used for visual representation in skill tables
 */
export function getSkillIcon(category: string, skillName: string): JSX.Element {
  const iconMap: Record<string, JSX.Element> = {
    // Body skills
    athletics: <GiDiscobolus size={25} />,
    acrobatics: <GiJumpAcross size={25} />,
    juggleries: <GiNunFace size={25} />,
    climbing: <GiMountainClimbing size={25} />,
    bodyControl: <GiBodyBalance size={25} />,
    riding: <GiHorseHead size={25} />,
    sneaking: <GiHoodedFigure size={25} />,
    swimming: <GiSwimfins size={25} />,
    selfControl: <GiSpikedHalo size={25} />,
    hiding: <GiHoodedAssassin size={25} />,
    singing: <GiSing size={25} />,
    sharpnessOfSenses: <GiAwareness size={25} />,
    imitatingVoices: <GiScreaming size={25} />,
    dancing: <GiHumanPyramid size={25} />,
    quaffing: <GiBeerStein size={25} />,
    pickpocketing: <GiHand size={25} />,

    // Social skills
    seduction: <GiWrappedHeart size={25} />,
    etiquette: <GiGraduateCap size={25} />,
    teaching: <GiTeacher size={25} />,
    acting: <GiCarnivalMask size={25} />,
    writtenExpression: <GiPencil size={25} />,
    disguise: <GiDominoMask size={25} />,
    streetKnowledge: <GiGooeySword size={25} />,
    knowledgeOfHumanNature: <GiBackup size={25} />,
    persuading: <GiTalk size={25} />,
    convincing: <GiTakeMyMoney size={25} />,
    bargaining: <GiCoinflip size={25} />,

    // Nature skills
    tracking: <GiDeerTrack size={25} />,
    knottingSkills: <GiRopeCoil size={25} />,
    trapping: <GiMantrap size={25} />,
    fishing: <GiFishing size={25} />,
    orientation: <GiPathDistance size={25} />,
    wildernessLife: <GiCampfire size={25} />,

    // Knowledge skills
    anatomy: <GiAnatomy size={25} />,
    architecture: <GiBrickWall size={25} />,
    geography: <GiTreasureMap size={25} />,
    history: <GiInspiration size={25} />,
    petrology: <GiStonePile size={25} />,
    botany: <GiPlantSeed size={25} />,
    philosophy: <GiInternalOrgan size={25} />,
    astronomy: <GiFallingStar size={25} />,
    mathematics: <GiCalculator size={25} />,
    knowledgeOfTheLaw: <GiInjustice size={25} />,
    estimating: <GiHistogram size={25} />,
    zoology: <GiBestialFangs size={25} />,
    technology: <GiTinker size={25} />,
    chemistry: <GiChemicalDrop size={25} />,
    warfare: <GiAxeSword size={25} />,
    itSkills: <GiComputing size={25} />,
    mechanics: <GiMonkeyWrench size={25} />,
    craftsmanship: <Gi3dHammer size={25} />,

    // Handcraft skills
    training: <GiBearHead size={25} />,
    foodProcessing: <GiField size={25} />,
    metalwork: <GiBowString size={25} />,
    stonework: <GiBrickWall size={25} />,
    alcoholProduction: <GiBeerHorn size={25} />,
    steeringVehicles: <GiRaceCar size={25} />,
    cheating: <GiCardExchange size={25} />,
    fineMechanics: <GiMechanicalArm size={25} />,
    butchery: <GiMeatCleaver size={25} />,
    leatherProcessing: <GiAnimalHide size={25} />,
    firstAid: <GiFirstAidKit size={25} />,
    calmingSbDown: <GiDespair size={25} />,
    woodwork: <GiWoodAxe size={25} />,
    cooking: <GiCookingPot size={25} />,
    fabricProcessing: <GiSewingString size={25} />,
    drawingAndPainting: <GiPencilBrush size={25} />,
    makingMusic: <GiMusicalScore size={25} />,
    lockpicking: <GiCombinationLock size={25} />,
    languagesAndScripts: <GiBookmark size={25} />,
  };

  return iconMap[skillName] || <GiRoundTable size={25} />;
}
